export const datas = [
    {
        id: 1,
        ProfileView: 7,
        PostView: 3,
        TotalComments: 90,
        TotalVieosViews: 20,
        TotalProjectViews: 30,
        TotalLikes: 50,
    },
    {
        id: 2,
        ProfileView: 20,
        PostView: 55,
        TotalComments: 12,
        TotalVieosViews: 50,
        TotalProjectViews: 70,
        TotalLikes: 44,
    },
    {
        id: 3,
        ProfileView: 24,
        PostView: 54,
        TotalComments: 104,
        TotalVieosViews: 204,
        TotalProjectViews: 304,
        TotalLikes: 404,
    },
    {
        id: 41,
        ProfileView: 12,
        PostView: 15,
        TotalComments: 110,
        TotalVieosViews: 120,
        TotalProjectViews: 130,
        TotalLikes: 140,
    },
    {
        id: 25,
        ProfileView: 22,
        PostView: 25,
        TotalComments: 210,
        TotalVieosViews: 220,
        TotalProjectViews: 230,
        TotalLikes: 240,
    }
];